# version: '3.4'
services:
  api:
    build:
      context: .
      target: development
      # dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # to avoid installing node_modules in the host machine
    ports:
      - "3000:3000"
    command: npm run dev